name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      run: docker login -u  ${{ secrets.docker_user }} -p  ${{ secrets.docker_pass }}
    - name: Build the Spark Base Image
      run: docker build -f ./Dockerfile . -t  spark_base_image:$(date +%s)
    - name: Push Spark Base image
      run: docker push spark_base_image:$(date +%s)
